[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^7.4.2
  links2004/WebSockets @ ^2.6.1
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
